const state = { city: 'both', category: 'all', query: '', view: 'calendar', events: [], window: { start: '2026-09-18', end: '2026-11-18' } };
const DAY = 86400000;
const parse = value => new Date(value);
const dateKey = date => date.toISOString().slice(0, 10);
const formatDay = date => new Intl.DateTimeFormat('en-GB', { weekday:'short', day:'numeric', month:'short' }).format(date);
const time = event => event.allDay ? 'All day' : `${parse(event.start).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}–${parse(event.end).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}`;
const rangeDays = (start,end) => { const dates=[]; let d=new Date(`${start}T12:00`), final=new Date(`${end}T12:00`); while(d<=final){dates.push(dateKey(d));d.setDate(d.getDate()+1)} return dates };
function matches(event) { const search = `${event.title} ${event.venue} ${event.category}`.toLowerCase(); return (state.city==='both'||event.city===state.city) && (state.category==='all'||event.category===state.category) && search.includes(state.query.toLowerCase()) }
function isoLocal(date){ return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}T${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}` }
function expandRecurring(event){
  if(!event.recurrenceRule) return [event];
  const copies=[], duration=parse(event.end)-parse(event.start), first=parse(event.start), until=parse(`${state.window.end}T23:59`);
  for(let d=new Date(first);d<=until;d.setDate(d.getDate()+7)) copies.push({...event,id:`${event.id}--${dateKey(d)}`,start:isoLocal(d),end:isoLocal(new Date(+d+duration)),baseId:event.id});
  return copies;
}
function visibleEvents(){ return state.events.filter(matches).flatMap(expandRecurring).sort((a,b)=>parse(a.start)-parse(b.start)) }
function monthDates(year, month){ const days=new Date(year,month+1,0).getDate(), offset=(new Date(year,month,1).getDay()+6)%7; return Array.from({length:offset+days},(_,i)=>i<offset?null:new Date(year,month,i-offset+1)) }
function eventOn(event,key){ return key >= event.start.slice(0,10) && key <= event.end.slice(0,10) }
function eventChip(event){ return `<button class="event-chip city-${event.city} ${event.recurrenceRule?'recurring':''}" data-event="${event.id}" title="${event.title}">${event.title}</button>` }
function calendar(){ const items=visibleEvents(); const windowStart=parse(`${state.window.start}T00:00`), windowEnd=parse(`${state.window.end}T23:59`), months=[]; for(let d=new Date(windowStart.getFullYear(),windowStart.getMonth(),1);d<=windowEnd;d=new Date(d.getFullYear(),d.getMonth()+1,1))months.push([d.getFullYear(),d.getMonth()]); document.querySelector('#month-title').textContent=`${new Intl.DateTimeFormat('en-GB',{month:'long'}).format(windowStart)} — ${new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(windowEnd)}`; document.querySelector('#calendar-view').innerHTML=months.map(([y,m])=>{ const dates=monthDates(y,m); const name=new Intl.DateTimeFormat('en-GB',{month:'long',year:'numeric'}).format(new Date(y,m,1)); return `<section class="month-block"><div class="month-label"><h3>${name}</h3><span></span></div><div class="weekday-row">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<span>${x}</span>`).join('')}</div><div class="day-grid">${dates.map(d=>{if(!d)return '<div class="day empty"></div>';const key=dateKey(d), dayEvents=items.filter(e=>eventOn(e,key)), valid=d>=windowStart&&d<=windowEnd; const today=key===dateKey(new Date()); return `<div class="day ${today?'today':''} ${valid?'':'empty'}"><span class="day-number">${d.getDate()}</span>${valid?dayEvents.slice(0,3).map(eventChip).join(''):''}${dayEvents.length>3?`<button class="more-events" data-date="${key}">+${dayEvents.length-3} more</button>`:''}</div>`}).join('')}</div></section>`}).join(''); }
function agenda(){ const events=visibleEvents(); const groups={}; events.forEach(e=>{rangeDays(e.start.slice(0,10),e.end.slice(0,10)).forEach(key=>{ if(key>=state.window.start&&key<=state.window.end){(groups[key]??=[]).push(e)} }) }); document.querySelector('#agenda-view').innerHTML=Object.entries(groups).map(([key,items])=>`<div class="agenda-day"><div class="agenda-date">${formatDay(new Date(`${key}T12:00`))}</div><div class="agenda-items">${items.map(e=>`<button class="agenda-item ${e.city}" data-event="${e.id}"><span><strong>${e.title}</strong><small>${e.venue}</small></span><small>${time(e)}</small></button>`).join('')}</div></div>`).join('')||'<p class="small-copy">No events match these filters.</p>'; }
function conflicts(){ const events=visibleEvents().filter(e=>!e.allDay); const conflicts=[]; for(let i=0;i<events.length;i++)for(let j=i+1;j<events.length;j++){ const a=events[i],b=events[j]; if(parse(a.start)<parse(b.end)&&parse(b.start)<parse(a.end)) { const duplicate=conflicts.some(c=>c.ids.includes(a.id)&&c.ids.includes(b.id)); if(!duplicate) conflicts.push({a,b,ids:[a.id,b.id]}) } } const panel=document.querySelector('#conflict-list'); document.querySelector('#conflict-count').textContent=conflicts.length; panel.innerHTML=conflicts.slice(0,4).map(c=>`<article class="conflict-card" data-conflict="${c.a.id},${c.b.id}"><div class="conflict-time">${formatDay(parse(c.a.start))} · ${time(c.a)}</div><div class="conflict-event"><i class="city-dot ${c.a.city}"></i>${c.a.title}</div><div class="conflict-event"><i class="city-dot ${c.b.city}"></i>${c.b.title}</div></article>`).join('') || '<p class="small-copy">Nothing overlaps in the current view.</p>'; }
function recurring(){ const events=state.events.filter(e=>e.recurrenceRule&&matches(e)); document.querySelector('#recurring-list').innerHTML=events.map(e=>`<article class="recurring-card" data-event="${e.id}"><strong>${e.title}</strong><span>${e.recurrence}</span></article>`).join('')||'<p class="small-copy">No recurring events in this view.</p>'; }
function render(){ calendar(); agenda(); conflicts(); recurring(); const n=visibleEvents().length; document.querySelector('#event-count').textContent=`${n} listing${n===1?'':'s'} shown`; document.querySelector('#calendar-view').classList.toggle('hidden',state.view!=='calendar'); document.querySelector('#agenda-view').classList.toggle('hidden',state.view!=='agenda'); }
function showEvent(id){ const e=visibleEvents().find(x=>x.id===id)||state.events.find(x=>x.id===id); if(!e)return; document.querySelector('#dialog-content').innerHTML=`<p class="eyebrow">${e.city==='heidelberg'?'Heidelberg':'Mannheim'} · ${e.category}</p><h2>${e.title}</h2><div class="dialog-meta"><span>${formatDay(parse(e.start))}</span><span>${time(e)}</span><span>${e.venue}</span>${e.recurrence?`<span>↻ ${e.recurrence}</span>`:''}</div><p class="dialog-description">${e.description}</p><a class="source-link" href="${e.source}" target="_blank" rel="noreferrer">Open ${e.sourceName} →</a>`; document.querySelector('#event-dialog').showModal() }
document.addEventListener('click',e=>{const target=e.target.closest('[data-event]');if(target)showEvent(target.dataset.event);const city=e.target.closest('[data-city]');if(city){state.city=city.dataset.city;document.querySelectorAll('[data-city]').forEach(b=>b.classList.toggle('active',b===city));render()}const category=e.target.closest('[data-category]');if(category){state.category=category.dataset.category;document.querySelectorAll('[data-category]').forEach(b=>b.classList.toggle('active',b===category));render()}const view=e.target.closest('[data-view]');if(view){state.view=view.dataset.view;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===view));render()}if(e.target.closest('.dialog-close'))e.target.closest('dialog').close();if(e.target.id==='sources-button')document.querySelector('#sources-dialog').showModal();const more=e.target.closest('[data-date]');if(more){state.view='agenda';document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='agenda'));render();document.querySelector('.agenda-day')?.scrollIntoView({behavior:'smooth'})}});
document.querySelector('#search-input').addEventListener('input',e=>{state.query=e.target.value;render()});
fetch('./events.json').then(r=>r.json()).then(data=>{state.events=data.events; state.window=data.window||state.window; document.querySelector('#refresh-label').textContent=`Updated ${new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(parse(data.generatedAt))}`; render()}).catch(()=>{document.querySelector('#calendar-view').innerHTML='<p>Could not load the event calendar.</p>'});
